title: Ali Ahmed Habib
description: >-
  <a href="https://www.linkedin.com/in/ali-ahmed-habib-8483371b0/" target="_blank"><img src="https://img.shields.io/badge/LinkedIn-Connect-blue"/></a> 
  <br>
  <a href="mailto:eng.ali.ahmed00@gmail.com"><img src="https://img.shields.io/badge/Gmail-Contact-red"/> eng.ali.ahmed00@gmail.com</a>
  <br>
  <a href="tel:+201021418491"><img src="https://img.shields.io/badge/Phone-%2B201021418491-green"/></a>
  <br>
  <a href="https://www.datacamp.com/portfolio/ah2966629" target="_blank"><img src="https://img.shields.io/badge/DataCamp-Profile-03EF62"/></a>
  <br>
  <a href="https://leetcode.com/u/Ali2222/" target="_blank"><img src="https://img.shields.io/badge/LeetCode-Profile-orange"/></a>
  <br>
  <a href="https://www.hackerrank.com/profile/ah2966629" target="_blank"><img src="https://img.shields.io/badge/HackerRank-Profile-2EC866"/></a> 
  <br>
  <a href="https://www.coursera.org/user/cb80a9d8cdddb4622219fa3b536b75b7" target="_blank"><img src="https://img.shields.io/badge/Coursera-Profile-0056D2"/></a>
logo: "/image.png"
show_download: true
theme: jekyll-theme-minimal
